### ISSUE TITLE
Leave for another users does not work perfectly.

### ISSUE THREAD

**Issue by cheluskin** [cloudflare/orange#89]
When the user leaves the room by pressing the 'Leave' button, their image freezes for others, and it takes some time (3-10 sec) before their window disappears and a message that they have left. Occasionally, it works quickly. But more often, the image just freezes. Chrome macOS and Safari macOS.

**Comment by cheluskin** [comment]
> You can fix this by changing the DurableObject code like so:
> 
> ```ts
> 	async onClose(
> 		connection: Connection<User>,
> 		_code: number,
> 		_reason: string,
> 		wasClean: boolean
> 	): Promise<void> {
> 		console.log(
> 			`Connection closed ${wasClean ? 'cleanly' : 'unexpectedly'}`,
> 			connection.id
> 		)
> 		try {
> 			await this.ctx.storage.delete(`session-${connection.id}`)
> 			await this.broadcastRoomState()
> 		} catch (err) {
> 			console.warn(`Failed to delete session session-${connection.id} on close`)
> 		}
> 	}
> 
> 	async onError(connection: Connection<User>, error: unknown): Promise<void> {
> 		console.error('Connection error', connection.id, error)
> 		try {
> 			await this.ctx.storage.delete(`session-${connection.id}`)
> 			await this.broadcastRoomState()
> 		} catch (err) {
> 			console.warn(`Failed to delete session session-${connection.id} on error`)
> 		}
> 	}
> ```
> 
> This is in the `app/durableObjects/ChatRoom.server.ts` file.

Thank you, it works.

**Comment by third774** [comment]
Hey, y'all — thanks for reporting this. The reason we don't rely on the `onClose` handler in `ChatRoom.server.ts` is because we don't want brief disconnects to register as the user having left and rejoined the room, which then requires everyone to pull their tracks again.

I've put a fix in place that will ensure the `userLeft` event is fired whenever the room is unmounting, and it _should_ take care of this. Please let me know if you have experience any other issues! 🙏🏻
